language: go

go:
  - stable

install:
  - go get github.com/spf13/hugo

script:
  - hugo

deploy:
  provider: pages
  skip-cleanup: true
  keep-history: false
  github-token: $GITHUB_TOKEN
  local-dir: public
  target-branch: master
  # committer-from-gh: true
  verbose: true
  on:
    branch: develop
