language: go

sudo: false
dist: trusty

cache:
  yarn: true

go:
  - stable

node_js:
  - lts/*

install:
  - go get github.com/spf13/hugo
  - yarn install --non-interactive

script:
  - yarn build
  - hugo

deploy:
  edge:
    branch: v1.8.47
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: public
  target-branch: master
  committer-from-gh: true
  verbose: true
  on:
    branch: develop
