language: go

go:
  - stable

install:
  - go get github.com/spf13/hugo

script:
  - hugo

deploy:
  edge:
    branch: v1.8.47
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: public
  target-branch: master
  committer-from-gh: true
  verbose: true
  on:
    branch: develop
