baseURL = "https://kolybasov.github.io"
languageCode = "en-us"
title = "Mykola Basov's Blog"

# Syntax highlight
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
pygmentsOptions = "linenos=table"

enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true

[params]
  githubLink = "https://github.com/kolybasov"
  githubRepo = "kolybasov.github.io"

[blackfriday]
  hrefTargetBlank = true
